# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_windows_ui.ui'
#
# Created: Tue Dec 17 11:41:01 2019
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(958, 952)
        self.centralwidget = QtGui.QWidget(MainWindow)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Agency FB"))
        font.setPointSize(12)
        self.centralwidget.setFont(font)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.groupBox_dev1 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_dev1.setGeometry(QtCore.QRect(40, 10, 341, 271))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Agency FB"))
        font.setPointSize(10)
        self.groupBox_dev1.setFont(font)
        self.groupBox_dev1.setObjectName(_fromUtf8("groupBox_dev1"))
        self.comboBox_dev1_port = QtGui.QComboBox(self.groupBox_dev1)
        self.comboBox_dev1_port.setGeometry(QtCore.QRect(120, 20, 201, 31))
        self.comboBox_dev1_port.setObjectName(_fromUtf8("comboBox_dev1_port"))
        self.comboBox_dev1_port.addItem(_fromUtf8(""))
        self.comboBox_dev1_rate = QtGui.QComboBox(self.groupBox_dev1)
        self.comboBox_dev1_rate.setGeometry(QtCore.QRect(120, 60, 201, 31))
        self.comboBox_dev1_rate.setObjectName(_fromUtf8("comboBox_dev1_rate"))
        self.comboBox_dev1_rate.addItem(_fromUtf8(""))
        self.comboBox_dev1_rate.addItem(_fromUtf8(""))
        self.comboBox_dev1_rate.addItem(_fromUtf8(""))
        self.comboBox_dev1_rate.addItem(_fromUtf8(""))
        self.comboBox_dev1_rate.addItem(_fromUtf8(""))
        self.comboBox_dev1_rate.addItem(_fromUtf8(""))
        self.comboBox_dev1_parity = QtGui.QComboBox(self.groupBox_dev1)
        self.comboBox_dev1_parity.setGeometry(QtCore.QRect(120, 140, 201, 31))
        self.comboBox_dev1_parity.setObjectName(_fromUtf8("comboBox_dev1_parity"))
        self.comboBox_dev1_parity.addItem(_fromUtf8(""))
        self.comboBox_dev1_parity.addItem(_fromUtf8(""))
        self.comboBox_dev1_parity.addItem(_fromUtf8(""))
        self.comboBox_dev1_parity.addItem(_fromUtf8(""))
        self.comboBox_dev1_parity.addItem(_fromUtf8(""))
        self.label = QtGui.QLabel(self.groupBox_dev1)
        self.label.setGeometry(QtCore.QRect(20, 30, 101, 18))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.groupBox_dev1)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 91, 18))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.groupBox_dev1)
        self.label_3.setGeometry(QtCore.QRect(20, 150, 101, 18))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.groupBox_dev1)
        self.label_4.setGeometry(QtCore.QRect(20, 190, 101, 21))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.groupBox_dev1)
        self.label_5.setGeometry(QtCore.QRect(20, 227, 101, 21))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.comboBox_dev1_stopbit = QtGui.QComboBox(self.groupBox_dev1)
        self.comboBox_dev1_stopbit.setGeometry(QtCore.QRect(120, 180, 201, 31))
        self.comboBox_dev1_stopbit.setObjectName(_fromUtf8("comboBox_dev1_stopbit"))
        self.comboBox_dev1_stopbit.addItem(_fromUtf8(""))
        self.comboBox_dev1_stopbit.addItem(_fromUtf8(""))
        self.comboBox_dev1_stopbit.addItem(_fromUtf8(""))
        self.comboBox_dev1_flow = QtGui.QComboBox(self.groupBox_dev1)
        self.comboBox_dev1_flow.setGeometry(QtCore.QRect(120, 220, 201, 31))
        self.comboBox_dev1_flow.setObjectName(_fromUtf8("comboBox_dev1_flow"))
        self.comboBox_dev1_flow.addItem(_fromUtf8(""))
        self.comboBox_dev1_flow.addItem(_fromUtf8(""))
        self.comboBox_dev1_flow.addItem(_fromUtf8(""))
        self.comboBox_dev1_data = QtGui.QComboBox(self.groupBox_dev1)
        self.comboBox_dev1_data.setGeometry(QtCore.QRect(120, 100, 201, 31))
        self.comboBox_dev1_data.setObjectName(_fromUtf8("comboBox_dev1_data"))
        self.comboBox_dev1_data.addItem(_fromUtf8(""))
        self.comboBox_dev1_data.addItem(_fromUtf8(""))
        self.label_6 = QtGui.QLabel(self.groupBox_dev1)
        self.label_6.setGeometry(QtCore.QRect(20, 110, 101, 18))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.textEdit_console = QtGui.QTextEdit(self.centralwidget)
        self.textEdit_console.setGeometry(QtCore.QRect(40, 310, 881, 531))
        self.textEdit_console.setObjectName(_fromUtf8("textEdit_console"))
        self.lineEdit = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(40, 860, 511, 31))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.pushButton_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(730, 860, 191, 31))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.groupBox_dev2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_dev2.setGeometry(QtCore.QRect(400, 10, 341, 271))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Agency FB"))
        font.setPointSize(10)
        self.groupBox_dev2.setFont(font)
        self.groupBox_dev2.setObjectName(_fromUtf8("groupBox_dev2"))
        self.comboBox_dev2_port = QtGui.QComboBox(self.groupBox_dev2)
        self.comboBox_dev2_port.setGeometry(QtCore.QRect(120, 20, 201, 31))
        self.comboBox_dev2_port.setObjectName(_fromUtf8("comboBox_dev2_port"))
        self.comboBox_dev2_port.addItem(_fromUtf8(""))
        self.comboBox_dev2_rate = QtGui.QComboBox(self.groupBox_dev2)
        self.comboBox_dev2_rate.setGeometry(QtCore.QRect(120, 60, 201, 31))
        self.comboBox_dev2_rate.setObjectName(_fromUtf8("comboBox_dev2_rate"))
        self.comboBox_dev2_rate.addItem(_fromUtf8(""))
        self.comboBox_dev2_rate.addItem(_fromUtf8(""))
        self.comboBox_dev2_rate.addItem(_fromUtf8(""))
        self.comboBox_dev2_rate.addItem(_fromUtf8(""))
        self.comboBox_dev2_rate.addItem(_fromUtf8(""))
        self.comboBox_dev2_rate.addItem(_fromUtf8(""))
        self.comboBox_dev2_parity = QtGui.QComboBox(self.groupBox_dev2)
        self.comboBox_dev2_parity.setGeometry(QtCore.QRect(120, 140, 201, 31))
        self.comboBox_dev2_parity.setObjectName(_fromUtf8("comboBox_dev2_parity"))
        self.comboBox_dev2_parity.addItem(_fromUtf8(""))
        self.comboBox_dev2_parity.addItem(_fromUtf8(""))
        self.comboBox_dev2_parity.addItem(_fromUtf8(""))
        self.comboBox_dev2_parity.addItem(_fromUtf8(""))
        self.comboBox_dev2_parity.addItem(_fromUtf8(""))
        self.label_7 = QtGui.QLabel(self.groupBox_dev2)
        self.label_7.setGeometry(QtCore.QRect(20, 30, 101, 18))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.groupBox_dev2)
        self.label_8.setGeometry(QtCore.QRect(20, 70, 91, 18))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.groupBox_dev2)
        self.label_9.setGeometry(QtCore.QRect(20, 150, 101, 18))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.groupBox_dev2)
        self.label_10.setGeometry(QtCore.QRect(20, 190, 101, 21))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.groupBox_dev2)
        self.label_11.setGeometry(QtCore.QRect(20, 227, 101, 21))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.comboBox_dev2_stopbit = QtGui.QComboBox(self.groupBox_dev2)
        self.comboBox_dev2_stopbit.setGeometry(QtCore.QRect(120, 180, 201, 31))
        self.comboBox_dev2_stopbit.setObjectName(_fromUtf8("comboBox_dev2_stopbit"))
        self.comboBox_dev2_stopbit.addItem(_fromUtf8(""))
        self.comboBox_dev2_stopbit.addItem(_fromUtf8(""))
        self.comboBox_dev2_stopbit.addItem(_fromUtf8(""))
        self.comboBox_dev2_flow = QtGui.QComboBox(self.groupBox_dev2)
        self.comboBox_dev2_flow.setGeometry(QtCore.QRect(120, 220, 201, 31))
        self.comboBox_dev2_flow.setObjectName(_fromUtf8("comboBox_dev2_flow"))
        self.comboBox_dev2_flow.addItem(_fromUtf8(""))
        self.comboBox_dev2_flow.addItem(_fromUtf8(""))
        self.comboBox_dev2_flow.addItem(_fromUtf8(""))
        self.comboBox_dev2_data = QtGui.QComboBox(self.groupBox_dev2)
        self.comboBox_dev2_data.setGeometry(QtCore.QRect(120, 100, 201, 31))
        self.comboBox_dev2_data.setObjectName(_fromUtf8("comboBox_dev2_data"))
        self.comboBox_dev2_data.addItem(_fromUtf8(""))
        self.comboBox_dev2_data.addItem(_fromUtf8(""))
        self.label_12 = QtGui.QLabel(self.groupBox_dev2)
        self.label_12.setGeometry(QtCore.QRect(20, 110, 101, 18))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.pushButton_connect = QtGui.QPushButton(self.centralwidget)
        self.pushButton_connect.setGeometry(QtCore.QRect(760, 20, 161, 81))
        self.pushButton_connect.setObjectName(_fromUtf8("pushButton_connect"))
        self.comboBox_select = QtGui.QComboBox(self.centralwidget)
        self.comboBox_select.setGeometry(QtCore.QRect(570, 860, 151, 31))
        self.comboBox_select.setObjectName(_fromUtf8("comboBox_select"))
        self.comboBox_select.addItem(_fromUtf8(""))
        self.comboBox_select.addItem(_fromUtf8(""))
        self.pushButton_clear = QtGui.QPushButton(self.centralwidget)
        self.pushButton_clear.setGeometry(QtCore.QRect(760, 200, 161, 81))
        self.pushButton_clear.setObjectName(_fromUtf8("pushButton_clear"))
        self.pushButton_disconnect = QtGui.QPushButton(self.centralwidget)
        self.pushButton_disconnect.setGeometry(QtCore.QRect(760, 110, 161, 81))
        self.pushButton_disconnect.setObjectName(_fromUtf8("pushButton_disconnect"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 958, 31))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Serial Forwarding", None))
        self.groupBox_dev1.setTitle(_translate("MainWindow", "Host", None))
        self.comboBox_dev1_port.setItemText(0, _translate("MainWindow", "PORT", None))
        self.comboBox_dev1_rate.setItemText(0, _translate("MainWindow", "115200", None))
        self.comboBox_dev1_rate.setItemText(1, _translate("MainWindow", "9600", None))
        self.comboBox_dev1_rate.setItemText(2, _translate("MainWindow", "14400", None))
        self.comboBox_dev1_rate.setItemText(3, _translate("MainWindow", "19200", None))
        self.comboBox_dev1_rate.setItemText(4, _translate("MainWindow", "38400", None))
        self.comboBox_dev1_rate.setItemText(5, _translate("MainWindow", "57600", None))
        self.comboBox_dev1_parity.setItemText(0, _translate("MainWindow", "none", None))
        self.comboBox_dev1_parity.setItemText(1, _translate("MainWindow", "odd", None))
        self.comboBox_dev1_parity.setItemText(2, _translate("MainWindow", "even", None))
        self.comboBox_dev1_parity.setItemText(3, _translate("MainWindow", "mark", None))
        self.comboBox_dev1_parity.setItemText(4, _translate("MainWindow", "space", None))
        self.label.setText(_translate("MainWindow", "Port : ", None))
        self.label_2.setText(_translate("MainWindow", "Speed :", None))
        self.label_3.setText(_translate("MainWindow", "Parity :", None))
        self.label_4.setText(_translate("MainWindow", "StopBit :", None))
        self.label_5.setText(_translate("MainWindow", "Flow Contorl :", None))
        self.comboBox_dev1_stopbit.setItemText(0, _translate("MainWindow", "1 bit", None))
        self.comboBox_dev1_stopbit.setItemText(1, _translate("MainWindow", "1.5 bit", None))
        self.comboBox_dev1_stopbit.setItemText(2, _translate("MainWindow", "2 bit", None))
        self.comboBox_dev1_flow.setItemText(0, _translate("MainWindow", "none", None))
        self.comboBox_dev1_flow.setItemText(1, _translate("MainWindow", "Xon/Xoff", None))
        self.comboBox_dev1_flow.setItemText(2, _translate("MainWindow", "hardware", None))
        self.comboBox_dev1_data.setItemText(0, _translate("MainWindow", "8 bit", None))
        self.comboBox_dev1_data.setItemText(1, _translate("MainWindow", "7 bit", None))
        self.label_6.setText(_translate("MainWindow", "Data :", None))
        self.pushButton_2.setText(_translate("MainWindow", "Send", None))
        self.groupBox_dev2.setTitle(_translate("MainWindow", "Remote", None))
        self.comboBox_dev2_port.setItemText(0, _translate("MainWindow", "PORT", None))
        self.comboBox_dev2_rate.setItemText(0, _translate("MainWindow", "115200", None))
        self.comboBox_dev2_rate.setItemText(1, _translate("MainWindow", "9600", None))
        self.comboBox_dev2_rate.setItemText(2, _translate("MainWindow", "14400", None))
        self.comboBox_dev2_rate.setItemText(3, _translate("MainWindow", "19200", None))
        self.comboBox_dev2_rate.setItemText(4, _translate("MainWindow", "38400", None))
        self.comboBox_dev2_rate.setItemText(5, _translate("MainWindow", "57600", None))
        self.comboBox_dev2_parity.setItemText(0, _translate("MainWindow", "none", None))
        self.comboBox_dev2_parity.setItemText(1, _translate("MainWindow", "odd", None))
        self.comboBox_dev2_parity.setItemText(2, _translate("MainWindow", "even", None))
        self.comboBox_dev2_parity.setItemText(3, _translate("MainWindow", "mark", None))
        self.comboBox_dev2_parity.setItemText(4, _translate("MainWindow", "space", None))
        self.label_7.setText(_translate("MainWindow", "Port :", None))
        self.label_8.setText(_translate("MainWindow", "Speed :", None))
        self.label_9.setText(_translate("MainWindow", "Parity :", None))
        self.label_10.setText(_translate("MainWindow", "StopBit :", None))
        self.label_11.setText(_translate("MainWindow", "Flow Control :", None))
        self.comboBox_dev2_stopbit.setItemText(0, _translate("MainWindow", "1 bit", None))
        self.comboBox_dev2_stopbit.setItemText(1, _translate("MainWindow", "1.5 bit", None))
        self.comboBox_dev2_stopbit.setItemText(2, _translate("MainWindow", "2 bit", None))
        self.comboBox_dev2_flow.setItemText(0, _translate("MainWindow", "none", None))
        self.comboBox_dev2_flow.setItemText(1, _translate("MainWindow", "Xon/Xoff", None))
        self.comboBox_dev2_flow.setItemText(2, _translate("MainWindow", "hardware", None))
        self.comboBox_dev2_data.setItemText(0, _translate("MainWindow", "8 bit", None))
        self.comboBox_dev2_data.setItemText(1, _translate("MainWindow", "7 bit", None))
        self.label_12.setText(_translate("MainWindow", "Data :", None))
        self.pushButton_connect.setText(_translate("MainWindow", "Connect", None))
        self.comboBox_select.setItemText(0, _translate("MainWindow", "host", None))
        self.comboBox_select.setItemText(1, _translate("MainWindow", "remote", None))
        self.pushButton_clear.setText(_translate("MainWindow", "Clear Console", None))
        self.pushButton_disconnect.setText(_translate("MainWindow", "DisConnect", None))

